name: Echollama Verbose Integration Test

on: [push, pull_request]

jobs:
  live-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build echollama
        run: go build -o echollama .

      - name: Start echollama server (background)
        run: |
          ./echollama serve &
          sleep 8

      - name: Load tiny test model
        run: |
          ./echollama pull qwen2.5:0.5b
          # Store model info in models directory to show it's "permanently" available
          mkdir -p models
          echo "qwen2.5:0.5b" > models/active-test-model.txt
          sleep 2

      - name: Send timestamped JSON requests (verbose)
        run: |
          TS1=$(date --iso-8601=ns)
          TS2=$(date --iso-8601=ns)
          # Verbose curl for first timestamp
          curl -v -X POST http://localhost:11434/api/generate \
            -H 'Content-Type: application/json' \
            -d '{
                  "model": "qwen2.5:0.5b",
                  "prompt": "TIMESTAMP1: '$TS1'",
                  "stream": false
                }' | tee response1.json
          # Verbose curl for second timestamp
          curl -v -X POST http://localhost:11434/api/generate \
            -H 'Content-Type: application/json' \
            -d '{
                  "model": "qwen2.5:0.5b",
                  "prompt": "TIMESTAMP2: '$TS2'",
                  "stream": false
                }' | tee response2.json

      - name: Show full JSON responses
        run: |
          cat response*.json

      - name: Show token info for both responses
        run: |
          jq .tokens response1.json
          jq .tokens response2.json

      - name: End-of-workflow verification (fail if responses missing tokens)
        run: |
          test "$(jq '.tokens | length' response1.json)" -gt 0
          test "$(jq '.tokens | length' response2.json)" -gt 0