name: Model Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      model:
        description: 'Model to test'
        required: false
        default: 'llama3.2:1b'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    
    - name: Build
      run: go build -o ollama .
    
    - name: Start server
      run: |
        ./ollama serve &
        sleep 10
    
    - name: Download model
      run: |
        MODEL="${{ github.event.inputs.model || 'llama3.2:1b' }}"
        ./ollama pull "$MODEL"
        mkdir -p models
        echo "$MODEL" > models/test-model.txt
        echo "MODEL=$MODEL" >> $GITHUB_ENV
    
    - name: Test model
      run: go run scripts/live-interactive-test.go "$MODEL"